apps/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('displaySheet/', views.displaySheet, name='displaySheet'),
]

kanjisheets/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.main.urls')),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/main/models.py
from django.db import models

# Create your models here.

apps/main/forms.py
from django import forms

INPUT_CLASSES = "bg-[#f5f5f5] rounded-lg"


class InputKanjiForm(forms.Form):
    kanjiInput = forms.CharField(widget=forms.Textarea(
        attrs={'class': "border-3 w-full bg-[#DCDCDC] rounded-lg", 'autofocus': 'autofocus', 'placeholder': '日本語を練習しましょう、チバリヨ～'}))
    columnasInput = forms.IntegerField(initial=7, widget=forms.NumberInput(
        attrs={'class': 'border-3 w-10 rounded bg-[#DCDCDC] p-1', 'placeholder': 'Enter number of columns.'}))

apps/main/views.py
from django.shortcuts import render, redirect
from .forms import InputKanjiForm
from django.http import HttpResponse
from django.views import View

from .utils import render_to_pdf
from .kanjivg_utils.utils import FindSvg

data = {
    "kanjiInput": "漢字",
}


def index(request):
    if request.method == 'POST':
        form = InputKanjiForm(request.POST)
        if form.is_valid():
            # kanjiInput get the data from the form
            kanjiInput = form.cleaned_data['kanjiInput']
            repetitions = form.cleaned_data['columnasInput']
            kanjiSvgCollection = []
            for element in kanjiInput:
                kanjiSvg = FindSvg(element)
                kanjiSvgCollection.append(kanjiSvg)
            pdf = render_to_pdf(
                'pdf2.html', {'kanjis': kanjiSvgCollection, 'repetitions': repetitions})
            return HttpResponse(pdf, content_type='application/pdf')
            # return render(request, "displaySheet.html", {'kanjis': kanjiSvgCollection})
    else:
        form = InputKanjiForm()
    return render(request, 'index.html', {'form': form})


def displaySheet(request):
    return render(request, 'displaySheet.html')

apps/main/templates/displaySheet.html
{% extends 'base.html' %} {% block title %} Kanji Sheets | Display strokes {% endblock %} {% block content %} {% load static %}
<div class="mt-10 p-10 bg-sky-600/[0.5] rounded-lg">
	{% for kanji in kanjis %}
	<div class="row">
		<img src="/static/img/kanji/{{ kanji }}" />
		<img style="opacity: 0.3" src="/static/img/kanji/{{ kanji }}" />
	</div>
	{% endfor %}
</div>
{% endblock %}

apps/main/templates/index.html
{% extends 'base.html' %} {% block title %}Kanji Sheets{% endblock %} {% block content %}
<style>
	#id_kanjiInput::placeholder {
		padding: 0.5rem;
	}
	#id_columnasInput {
		text-align: center;
	}
</style>
<div class="mt-10">
	<form method="post">
		{% csrf_token %}
		<div class="flex flex-col justify-center content-center mb-5">
			<p class="self-start mb-3">Enter the hiragana/katakana/kanji you want to include in the sheet:</p>
			{{ form.kanjiInput }}
			<div class="my-2 mr-2"><label for="id_columnasInput">Columns: </label>{{form.columnasInput}}</div>
		</div>
		<button
			type="submit"
			class="mb-10 inline-block rounded bg-primary px-6 pb-2 pt-2.5 text-xs font-medium uppercase leading-normal text-white shadow-[0_4px_9px_-4px_#3b71ca] transition duration-150 ease-in-out hover:bg-primary-600 hover:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)] focus:bg-primary-600 focus:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)] focus:outline-none focus:ring-0 active:bg-primary-700 active:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)] dark:shadow-[0_4px_9px_-4px_rgba(59,113,202,0.5)] dark:hover:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.2),0_4px_18px_0_rgba(59,113,202,0.1)] dark:focus:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.2),0_4px_18px_0_rgba(59,113,202,0.1)] dark:active:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.2),0_4px_18px_0_rgba(59,113,202,0.1)]"
		>
			Aceptar
		</button>
	</form>
</div>
{% endblock %}

apps/main/templates/pdf2.html
{% load static %} {% load my_filters %}

<html>
	<head>
		<meta charset="utf-8" />
		<title>PDF</title>
		<style></style>
	</head>

	<body>
		<table border="0.5">
			{% for kanji in kanjis %}
			<tr>
				<td><img src="media/kanji/{{ kanji }}" /></td>
				{% for i in repetitions|times %}
				<td></td>
				{% endfor %}
			</tr>
			{% endfor %}
		</table>
	</body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
	<head>
		{% load %} {% load static %}
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900&display=swap" rel="stylesheet" />
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/tw-elements/dist/css/tw-elements.min.css" />
		<link rel="stylesheet" href="{% static 'css/styles.css' %}" />
		<script src="https://cdn.tailwindcss.com/3.3.0"></script>
		<script>
			tailwind.config = {
				darkMode: 'class',
				theme: {
					fontFamily: {
						sans: ['Roboto', 'sans-serif'],
						body: ['Roboto', 'sans-serif'],
						mono: ['ui-monospace', 'monospace'],
					},
				},
				corePlugins: {
					preflight: false,
				},
			}
		</script>
		{% block head %} {% endblock %}
		<title>{% block title %}{% endblock %}</title>
	</head>

	<body class="flex flex-col">
		<header>
			<nav class="navbar">{% include 'partials/navbar.html' %}</nav>
		</header>

		<main class="grow w-2/3 m-auto" id="main">{% block content %} {% endblock %}</main>

		<footer id="footer">{% include 'partials/footer.html' %}</footer>

		<script src="https://cdn.jsdelivr.net/npm/tw-elements/dist/js/tw-elements.umd.min.js"></script>
	</body>
</html>

templates/partials/footer.html
<!--Footer container-->
<footer class="bg-cyan-600/[0.7] text-center text-white">
	<div class="container px-6 pt-6 mx-auto">
		<div class="mb-6 flex justify-center">
			<a
				href="#!"
				type="button"
				class="m-1 h-9 w-9 rounded-full border-2 border-white uppercase leading-normal text-white transition duration-150 ease-in-out hover:bg-black hover:bg-opacity-5 focus:outline-none focus:ring-0"
				data-te-ripple-init
				data-te-ripple-color="light"
			>
				<svg xmlns="http://www.w3.org/2000/svg" class="mx-auto h-full w-4" fill="currentColor" viewBox="0 0 24 24">
					<path d="M9 8h-3v4h3v12h5v-12h3.642l.358-4h-4v-1.667c0-.955.192-1.333 1.115-1.333h2.885v-5h-3.808c-3.596 0-5.192 1.583-5.192 4.615v3.385z" />
				</svg>
			</a>
			<a
				href="#!"
				type="button"
				class="m-1 h-9 w-9 rounded-full border-2 border-white uppercase leading-normal text-white transition duration-150 ease-in-out hover:bg-black hover:bg-opacity-5 focus:outline-none focus:ring-0"
				data-te-ripple-init
				data-te-ripple-color="light"
			>
				<svg xmlns="http://www.w3.org/2000/svg" class="mx-auto h-full w-4" fill="currentColor" viewBox="0 0 24 24">
					<path
						d="M7 11v2.4h3.97c-.16 1.029-1.2 3.02-3.97 3.02-2.39 0-4.34-1.979-4.34-4.42 0-2.44 1.95-4.42 4.34-4.42 1.36 0 2.27.58 2.79 1.08l1.9-1.83c-1.22-1.14-2.8-1.83-4.69-1.83-3.87 0-7 3.13-7 7s3.13 7 7 7c4.04 0 6.721-2.84 6.721-6.84 0-.46-.051-.81-.111-1.16h-6.61zm0 0 17 2h-3v3h-2v-3h-3v-2h3v-3h2v3h3v2z"
						fill-rule="evenodd"
						clip-rule="evenodd"
					/>
				</svg>
			</a>

			<a
				href="#!"
				type="button"
				class="m-1 h-9 w-9 rounded-full border-2 border-white uppercase leading-normal text-white transition duration-150 ease-in-out hover:bg-black hover:bg-opacity-5 focus:outline-none focus:ring-0"
				data-te-ripple-init
				data-te-ripple-color="light"
			>
				<svg xmlns="http://www.w3.org/2000/svg" class="mx-auto h-full w-4" fill="currentColor" viewBox="0 0 24 24">
					<path
						d="M12 2.163c3.204 0 3.584.012 4.85.07 3.252.148 4.771 1.691 4.919 4.919.058 1.265.069 1.645.069 4.849 0 3.205-.012 3.584-.069 4.849-.149 3.225-1.664 4.771-4.919 4.919-1.266.058-1.644.07-4.85.07-3.204 0-3.584-.012-4.849-.07-3.26-.149-4.771-1.699-4.919-4.92-.058-1.265-.07-1.644-.07-4.849 0-3.204.013-3.583.07-4.849.149-3.227 1.664-4.771 4.919-4.919 1.266-.057 1.645-.069 4.849-.069zm0-2.163c-3.259 0-3.667.014-4.947.072-4.358.2-6.78 2.618-6.98 6.98-.059 1.281-.073 1.689-.073 4.948 0 3.259.014 3.668.072 4.948.2 4.358 2.618 6.78 6.98 6.98 1.281.058 1.689.072 4.948.072 3.259 0 3.668-.014 4.948-.072 4.354-.2 6.782-2.618 6.979-6.98.059-1.28.073-1.689.073-4.948 0-3.259-.014-3.667-.072-4.947-.196-4.354-2.617-6.78-6.979-6.98-1.281-.059-1.69-.073-4.949-.073zm0 5.838c-3.403 0-6.162 2.759-6.162 6.162s2.759 6.163 6.162 6.163 6.162-2.759 6.162-6.163c0-3.403-2.759-6.162-6.162-6.162zm0 10.162c-2.209 0-4-1.79-4-4 0-2.209 1.791-4 4-4s4 1.791 4 4c0 2.21-1.791 4-4 4zm6.406-11.845c-.796 0-1.441.645-1.441 1.44s.645 1.44 1.441 1.44c.795 0 1.439-.645 1.439-1.44s-.644-1.44-1.439-1.44z"
					/>
				</svg>
			</a>

			<a
				href="#!"
				type="button"
				class="m-1 h-9 w-9 rounded-full border-2 border-white uppercase leading-normal text-white transition duration-150 ease-in-out hover:bg-black hover:bg-opacity-5 focus:outline-none focus:ring-0"
				data-te-ripple-init
				data-te-ripple-color="light"
			>
				<svg xmlns="http://www.w3.org/2000/svg" class="mx-auto h-full w-4" fill="currentColor" viewBox="0 0 24 24">
					<path
						d="M4.98 3.5c0 1.381-1.11 2.5-2.48 2.5s-2.48-1.119-2.48-2.5c0-1.38 1.11-2.5 2.48-2.5s2.48 1.12 2.48 2.5zm.02 4.5h-5v16h5v-16zm7.982 0h-4.968v16h4.969v-8.399c0-4.67 6.029-5.052 6.029 0v8.399h4.988v-10.131c0-7.88-8.922-7.593-11.018-3.714v-2.155z"
					/>
				</svg>
			</a>

			<a
				href="#!"
				type="button"
				class="m-1 h-9 w-9 rounded-full border-2 border-white uppercase leading-normal text-white transition duration-150 ease-in-out hover:bg-black hover:bg-opacity-5 focus:outline-none focus:ring-0"
				data-te-ripple-init
				data-te-ripple-color="light"
			>
				<svg xmlns="http://www.w3.org/2000/svg" class="mx-auto h-full w-4" fill="currentColor" viewBox="0 0 24 24">
					<path
						d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"
					/>
				</svg>
			</a>
		</div>
	</div>

	<!--Copyright section-->
	<div class="p-4 text-center" style="background-color: rgba(0, 0, 0, 0.2)">
		© 2023 Copyright:
		<a class="text-whitehite" href="https://tailwind-elements.com/">Tailwind Elements</a>
	</div>
</footer>

templates/partials/navbar.html
<!-- Navigation bar -->
{% load static %}
<nav
	class="relative flex w-full items-center justify-between bg-cyan-600/[0.7] py-2 text-white shadow-lg hover:text-slate-200 focus:text-slate-200 dark:bg-neutral-600 dark:text-neutral-200 md:flex-wrap md:justify-start"
	data-te-navbar-ref
>
	<div class="flex w-full flex-wrap items-center justify-between px-3">
		<div class="flex items-center">
			<!-- Hamburger menu button -->
			<button
				class="border-0 bg-transparent px-2 text-xl leading-none transition-shadow duration-150 ease-in-out hover:text-neutral-700 focus:text-neutral-700 dark:hover:text-white dark:focus:text-white lg:hidden"
				type="button"
				data-te-collapse-init
				data-te-target="#navbarSupportedContentX"
				aria-controls="navbarSupportedContentX"
				aria-expanded="false"
				aria-label="Toggle navigation"
			>
				<!-- Hamburger menu icon -->
				<span class="[&>svg]:w-5">
					<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="h-7 w-7">
						<path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
					</svg>
				</span>
			</button>
		</div>

		<!-- Navigation links -->
		<div class="!visible hidden grow basis-[100%] items-center lg:!flex lg:basis-auto" id="navbarSupportedContentX" data-te-collapse-item>
			<div class="w-2/3 m-auto flex">
				<ul class="mr-auto flex flex-col lg:flex-row" data-te-navbar-nav-ref>
					<li class="self-center mb-4 lg:mb-0 lg:pr-2" data-te-nav-item-ref>
						<a
							class="block text-xl transition duration-150 ease-in-out hover:text-neutral-700 focus:text-neutral-700 disabled:text-black/30 dark:hover:text-white dark:focus:text-white lg:p-2 [&.active]:text-black/90"
							href="{% url 'main:index' %}"
							data-te-nav-link-ref
							data-te-ripple-init
							data-te-ripple-color="light"
							>Home</a
						>
					</li>
					<li class="self-center mb-4 lg:mb-0 lg:pr-2" data-te-nav-item-ref>
						<a
							class="block text-xl transition duration-150 ease-in-out hover:text-neutral-700 focus:text-neutral-700 disabled:text-black/30 dark:hover:text-white dark:focus:text-white lg:p-2 [&.active]:text-black/90"
							href="{% url 'main:displaySheet' %}"
							data-te-nav-link-ref
							data-te-ripple-init
							data-te-ripple-color="light"
							>Display Kanji</a
						>
					</li>
					{% comment %}
					<li class="mb-4 lg:mb-0 lg:pr-2" data-te-nav-item-ref>
						<a
							class="block text-xl transition duration-150 ease-in-out hover:text-neutral-700 focus:text-neutral-700 disabled:text-black/30 dark:hover:text-white dark:focus:text-white lg:p-2 [&.active]:text-black/90"
							href="{% url 'main:pdf_view' %}"
							data-te-nav-link-ref
							data-te-ripple-init
							data-te-ripple-color="light"
							>Generate PDF</a
						>
					</li>
					{% endcomment %} {% comment %}
					<li class="mb-2 lg:mb-0 lg:pr-2" data-te-nav-item-ref>
						<a
							class="block text-xl transition duration-150 ease-in-out hover:text-neutral-700 focus:text-neutral-700 disabled:text-black/30 dark:hover:text-white dark:focus:text-white lg:p-2 [&.active]:text-black/90"
							href="#!"
							data-te-nav-link-ref
							data-te-ripple-init
							data-te-ripple-color="light"
							>About</a
						>
					</li>
					{% endcomment %}
				</ul>
				<div>
					<img width="125" src="{% static 'img/totoro_logo.png' %}" alt="" />
				</div>
			</div>
		</div>
	</div>
</nav>